# Generated by Django 5.0 on 2023-12-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_alter_todo_fineshed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="fineshed_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
