# Generated by Django 5.0 on 2023-12-29 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0004_alter_todo_fineshed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("surname", models.CharField(max_length=150)),
                ("nickname", models.CharField(blank=True, max_length=150, null=True)),
                ("email", models.EmailField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="todo",
            name="user_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_id",
                to="todos.userapi",
            ),
            preserve_default=False,
        ),
    ]
