# Generated by Django 5.0 on 2023-12-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0007_remove_todo_user_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ("fineshed_at", "deadline")},
        ),
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateField(verbose_name="Prazo Final:"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Título:"),
        ),
    ]
